id = "BSD-2-Clause"
name = "BSD 2-Clause \"Simplified\" License"
url = "https://spdx.org/licenses/BSD-2-Clause.html"

[terms]
requires_attribution = false
requires_license_notice = true
requires_source_disclosure = false
derivatives = "allowed"
requires_modification_notice = false
allows_commercial_use = true
allows_redistribution = true
manual_review = false
