//! `auditah add-license` — scaffold a license grid (`.toml`) in `LICENSES/`.

use std::path::{Path, PathBuf};

use error_stack::{Report, ResultExt};
use wherror::Error;

use crate::model::terms::LicenseTerms;
use crate::services::Services;

/// Error writing a license template.
#[derive(Debug, Error)]
#[error(debug)]
pub struct AddLicenseError;

/// Compute the on-disk path for a license grid: `<root>/LICENSES/<id>.toml`.
#[must_use]
pub fn license_grid_path(root: &Path, id: &str) -> PathBuf {
    root.join("LICENSES").join(format!("{id}.toml"))
}

/// Prefix a bare name with `LicenseRef-` if it isn't already a `LicenseRef-*` id.
///
/// `Foo` → `LicenseRef-Foo`; `LicenseRef-Foo` → `LicenseRef-Foo` (idempotent).
#[must_use]
pub fn license_ref_id(name: &str) -> String {
    if name.starts_with("LicenseRef-") {
        name.to_string()
    } else {
        format!("LicenseRef-{name}")
    }
}

/// Render a fully-commented license grid template for the given id.
///
/// Every `[terms]` field gets a `#` comment explaining what it means, and the
/// header explains the `id` ↔ `LICENSES/<id>.txt` relationship so the user knows
/// they must also drop the legal text alongside this grid. Defaults are the
/// permissive baseline ("use however you want"); the user edits as needed.
#[must_use]
pub fn render_license_template(id: &str) -> String {
    let terms = LicenseTerms::permissive();
    let mut s = String::new();

    // Header: explain the id + LicenseRef- + LICENSES/<id>.txt relationship.
    s.push_str("# License definition generated by `auditah add-license`.\n");
    s.push_str("#\n");
    s.push_str(
        "# The `id` is the canonical license identifier. For custom licenses it uses the\n",
    );
    s.push_str("# `LicenseRef-<Name>` form. auditah resolves a license by matching this `id`\n");
    s.push_str("# against the `license` field in an asset's attribution sidecar/manifest.\n");
    s.push_str("#\n");
    s.push_str("# In addition to this grid (`.toml`), the FULL LEGAL TEXT must live in a sibling\n");
    s.push_str("# file named `<id>.txt` in the same `LICENSES/` directory. audit FAILs until\n");
    s.push_str("# that file exists — so after editing this grid, create:\n");
    s.push_str("#\n");
    s.push_str(&format!("#     LICENSES/{id}.txt\n"));
    s.push_str("#\n");
    s.push_str("# with the complete license text, then fill out the fields below.\n");
    s.push('\n');

    s.push_str(&format!("id = \"{id}\"\n"));
    s.push_str("name = \"TODO: human-readable license name\"\n");
    s.push_str("url = \"TODO: canonical URL of the license\"\n");
    s.push('\n');

    s.push_str("[terms]\n");
    s.push_str("# You MUST attribute the author (audit verifies title + author + source are set).\n");
    s.push_str(&format!(
        "requires_attribution = {}\n",
        terms.requires_attribution
    ));
    s.push_str("# You MUST reproduce the license text in your distribution.\n");
    s.push_str(&format!(
        "requires_license_notice = {}\n",
        terms.requires_license_notice
    ));
    s.push_str(
        "# You MUST offer corresponding source code on distribution. Auto-unverifiable (FLAG).\n",
    );
    s.push_str(&format!(
        "requires_source_disclosure = {}\n",
        terms.requires_source_disclosure
    ));
    s.push_str(
        "# Derivatives dimension. One of:\n",
    );
    s.push_str("#   \"disallowed\"  — no derivatives permitted (CC-BY-ND).\n");
    s.push_str("#   \"allowed\"     — derivatives permitted under any terms (MIT, CC-BY, CC0).\n");
    s.push_str("#   \"share-alike\" — derivatives must use the same license (OFL, GPL, CC-BY-SA).\n");
    s.push_str(&format!("derivatives = \"{}\"\n", kebab(terms.derivatives)));
    s.push_str(
        "# If the asset is modified, you MUST state the modification in credits.\n",
    );
    s.push_str(&format!(
        "requires_modification_notice = {}\n",
        terms.requires_modification_notice
    ));
    s.push_str("# You MAY use this commercially.\n");
    s.push_str(&format!(
        "allows_commercial_use = {}\n",
        terms.allows_commercial_use
    ));
    s.push_str(
        "# You MAY redistribute (re-host / resell) the asset itself, not just ship it embedded.\n",
    );
    s.push_str(&format!(
        "allows_redistribution = {}\n",
        terms.allows_redistribution
    ));
    s.push_str(
        "# The license carries clauses the boolean grid cannot auto-verify (seat limits,\n",
    );
    s.push_str(
        "# territory, field-of-use, ...). FAILs the audit until the license id is listed in\n",
    );
    s.push_str("# `manual_review_acknowledged` in auditah.toml. License-only: not overridable.\n");
    s.push_str(&format!("manual_review = {}\n", terms.manual_review));

    s.push('\n');
    s.push_str("# Free-form notes, especially for bespoke/custom licenses. Optional.\n");
    s.push_str("# notes = \"...\"\n");

    s
}

/// Render a `Derivatives` variant to its kebab-case TOML string.
fn kebab(d: crate::model::terms::Derivatives) -> &'static str {
    use crate::model::terms::Derivatives::{Allowed, Disallowed, ShareAlike};
    match d {
        Disallowed => "disallowed",
        Allowed => "allowed",
        ShareAlike => "share-alike",
    }
}

/// Write the license grid template to `<root>/LICENSES/LicenseRef-<name>.toml`.
///
/// Refuses to overwrite an existing file. Returns the path that was written.
///
/// # Errors
///
/// Returns `AddLicenseError` if the target file already exists or writing fails.
pub fn write_license_template(
    services: &Services,
    root: &Path,
    name: &str,
) -> Result<PathBuf, Report<AddLicenseError>> {
    let id = license_ref_id(name);
    let path = license_grid_path(root, &id);
    if path.exists() {
        return Err(Report::new(AddLicenseError)
            .attach("license grid already exists; edit it directly or remove it first")
            .attach(path.display().to_string()));
    }
    let content = render_license_template(&id);
    services
        .fs
        .write(&path, &content)
        .change_context(AddLicenseError)
        .attach("failed to write license grid")?;
    Ok(path)
}
