//! `auditah add-license` — scaffold a license grid (`.toml`) in `LICENSES/`.

use std::fmt::Write;
use std::path::{Path, PathBuf};

use error_stack::{Report, ResultExt};
use wherror::Error;

use crate::model::terms::LicenseTerms;
use crate::services::Services;

/// Error writing a license template.
#[derive(Debug, Error)]
#[error(debug)]
pub struct AddLicenseError;

/// Compute the on-disk path for a license grid: `<root>/LICENSES/<id>.toml`.
#[must_use]
pub fn license_grid_path(root: &Path, id: &str) -> PathBuf {
    root.join("LICENSES").join(format!("{id}.toml"))
}

/// Prefix a bare name with `LicenseRef-` if it isn't already a `LicenseRef-*` id.
///
/// `Foo` → `LicenseRef-Foo`; `LicenseRef-Foo` → `LicenseRef-Foo` (idempotent).
#[must_use]
pub fn license_ref_id(name: &str) -> String {
    if name.starts_with("LicenseRef-") {
        name.to_string()
    } else {
        format!("LicenseRef-{name}")
    }
}

/// Render a fully-commented license grid template for the given id.
///
/// Every `[terms]` field gets a `#` comment explaining what it means, and the
/// header explains the `id` ↔ `LICENSES/<id>.txt` relationship so the user knows
/// they must also drop the legal text alongside this grid. Defaults are the
/// `default_fail()` baseline (maximally restrictive + `manual_review = true`):
/// the grid FAILs audit until the user fills in the real terms AND acknowledges
#[must_use]
#[allow(clippy::unwrap_used)] // writeln! to a String is infallible
pub fn render_license_template(id: &str) -> String {
    let terms = LicenseTerms::default_fail();
    let mut s = String::new();

    write_header(&mut s, id);
    write_id_fields(&mut s, id);
    write_terms(&mut s, &terms);

    s
}

/// Header: explain the `id` + `LicenseRef-` + LICENSES/<id>.txt relationship.
#[allow(clippy::unwrap_used)] // writeln! to a String is infallible
fn write_header(s: &mut String, id: &str) {
    writeln!(
        s,
        "# License definition generated by `auditah add-license`."
    )
    .unwrap();
    writeln!(s, "#").unwrap();
    writeln!(
        s,
        "# The `id` is the canonical license identifier. For custom licenses it uses the"
    )
    .unwrap();
    writeln!(
        s,
        "# `LicenseRef-<Name>` form. auditah resolves a license by matching this `id`"
    )
    .unwrap();
    writeln!(
        s,
        "# against the `license` field in an asset's attribution sidecar/manifest."
    )
    .unwrap();
    writeln!(s, "#").unwrap();
    writeln!(
        s,
        "# In addition to this grid (`.toml`), the FULL LEGAL TEXT must live in a sibling"
    )
    .unwrap();
    writeln!(
        s,
        "# file named `<id>.txt` in the same `LICENSES/` directory. audit FAILs until"
    )
    .unwrap();
    writeln!(
        s,
        "# that file exists — so after editing this grid, create:"
    )
    .unwrap();
    writeln!(s, "#").unwrap();
    writeln!(s, "#     LICENSES/{id}.txt").unwrap();
    writeln!(s, "#").unwrap();
    writeln!(
        s,
        "# with the complete license text. This grid FAILs audit until you fill in the real `[terms]` below AND add the id to `manual_review_acknowledged`."
    )
    .unwrap();
    writeln!(s).unwrap();
}

/// id / name / url fields.
#[allow(clippy::unwrap_used)] // writeln! to a String is infallible
fn write_id_fields(s: &mut String, id: &str) {
    writeln!(s, "id = \"{id}\"").unwrap();
    writeln!(s, "name = \"TODO: human-readable license name\"").unwrap();
    writeln!(s, "url = \"TODO: canonical URL of the license\"").unwrap();
    writeln!(s).unwrap();
}

/// `[terms]` table with a `#` comment above each field.
#[allow(clippy::unwrap_used)] // writeln! to a String is infallible
fn write_terms(s: &mut String, terms: &LicenseTerms) {
    writeln!(s, "[terms]").unwrap();
    write_commented_bool(
        s,
        "# You MUST attribute the author (audit verifies title + author + source are set).",
        "requires_attribution",
        terms.requires_attribution,
    );
    write_commented_bool(
        s,
        "# You MUST reproduce the license text in your distribution.",
        "requires_license_notice",
        terms.requires_license_notice,
    );
    write_commented_bool(
        s,
        "# You MUST offer corresponding source code on distribution. Auto-unverifiable (FLAG).",
        "requires_source_disclosure",
        terms.requires_source_disclosure,
    );
    writeln!(s, "# Derivatives dimension. One of:").unwrap();
    writeln!(
        s,
        "#   \"disallowed\"  — no derivatives permitted (CC-BY-ND)."
    )
    .unwrap();
    writeln!(
        s,
        "#   \"allowed\"     — derivatives permitted under any terms (MIT, CC-BY, CC0)."
    )
    .unwrap();
    writeln!(
        s,
        "#   \"share-alike\" — derivatives must use the same license (OFL, GPL, CC-BY-SA)."
    )
    .unwrap();
    writeln!(s, "derivatives = \"{}\"", kebab(terms.derivatives)).unwrap();
    write_commented_bool(
        s,
        "# If the asset is modified, you MUST state the modification in credits.",
        "requires_modification_notice",
        terms.requires_modification_notice,
    );
    write_commented_bool(
        s,
        "# You MAY use this commercially.",
        "allows_commercial_use",
        terms.allows_commercial_use,
    );
    write_commented_bool(
        s,
        "# You MAY redistribute (re-host / resell) the asset itself, not just ship it embedded.",
        "allows_redistribution",
        terms.allows_redistribution,
    );
    writeln!(
        s,
        "# The license carries clauses the boolean grid cannot auto-verify (seat limits,"
    )
    .unwrap();
    writeln!(
        s,
        "# territory, field-of-use, ...). FAILs the audit until the license id is listed in"
    )
    .unwrap();
    writeln!(
        s,
        "# `manual_review_acknowledged` in auditah.toml. License-only: not overridable."
    )
    .unwrap();
    writeln!(s, "manual_review = {}", terms.manual_review).unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "# Free-form notes, especially for bespoke/custom licenses. Optional."
    )
    .unwrap();
    writeln!(s, "# notes = \"...\"").unwrap();
}

/// Write a one-line `#` comment followed by a `field = value` boolean.
#[allow(clippy::unwrap_used)] // writeln! to a String is infallible
fn write_commented_bool(s: &mut String, comment: &str, field: &str, value: bool) {
    writeln!(s, "{comment}").unwrap();
    writeln!(s, "{field} = {value}").unwrap();
}

/// Render a `Derivatives` variant to its kebab-case TOML string.
fn kebab(d: crate::model::terms::Derivatives) -> &'static str {
    use crate::model::terms::Derivatives::{Allowed, Disallowed, ShareAlike};
    match d {
        Disallowed => "disallowed",
        Allowed => "allowed",
        ShareAlike => "share-alike",
    }
}

/// Write the license grid template to `<root>/LICENSES/LicenseRef-<name>.toml`.
///
/// Refuses to overwrite an existing file. Returns the path that was written.
///
/// # Errors
///
/// Returns `AddLicenseError` if the target file already exists or writing fails.
pub fn write_license_template(
    services: &Services,
    root: &Path,
    name: &str,
) -> Result<PathBuf, Report<AddLicenseError>> {
    let id = license_ref_id(name);
    let path = license_grid_path(root, &id);
    if path.exists() {
        return Err(Report::new(AddLicenseError)
            .attach("license grid already exists; edit it directly or remove it first")
            .attach(path.display().to_string()));
    }
    let content = render_license_template(&id);
    services
        .fs
        .write(&path, &content)
        .change_context(AddLicenseError)
        .attach("failed to write license grid")?;
    Ok(path)
}
