//! Project configuration (`auditah.toml`): commercial-use flag + exclude globs.

use std::fmt::Write;
use std::path::Path;

use error_stack::{Report, ResultExt};
use serde::{Deserialize, Serialize};
use wherror::Error;

use crate::services::FsService;

use crate::discovery::enumerator::ExcludeMatcher;

/// Error loading or parsing `auditah.toml`.
#[derive(Debug, Error)]
#[error(debug)]
pub struct ConfigError;

/// Project root configuration.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Config {
    /// Whether the consuming project is commercial. When true, assets whose
    /// effective terms have `allows_commercial_use = false` FAIL the audit.
    #[serde(default)]
    pub commercial_project: bool,
    /// Whether the project redistributes assets (re-hosts / resells the raw
    /// asset itself, not just shipping it embedded in a product). When true,
    /// assets whose effective terms have `allows_redistribution = false` FAIL.
    #[serde(default)]
    pub redistributes_assets: bool,
    /// SPDX license ids whose `manual_review` obligation has been reviewed and
    /// acknowledged for this project. An acknowledged id suppresses its
    /// `ManualReviewRequired` FAIL. Acknowledgment is permanent and silent.
    #[serde(default)]
    pub manual_review_acknowledged: Vec<String>,
    /// User-supplied glob patterns to exclude from enumeration (in addition to
    /// the built-in default excludes). Matched against paths relative to root.
    #[serde(default)]
    pub exclude: Vec<String>,
}

/// File name of the project config at the project root.
pub const CONFIG_FILENAME: &str = "auditah.toml";

/// Validate that the default + user exclude globs all compile.
///
/// Called eagerly in [`Config::load`] so an invalid glob in `auditah.toml`
/// fails fast at config load rather than panicking later during the audit walk.
/// The globs are re-compiled inside `build_excludes` at use time (defense in
/// depth: a `Config` constructed directly, bypassing `load`, is still caught there).
fn validate_excludes(exclude: &[String]) -> Result<(), Report<ConfigError>> {
    let patterns = crate::discovery::all_excludes(exclude);
    ExcludeMatcher::new(&patterns)
        .change_context(ConfigError)
        .attach("invalid exclude glob in auditah.toml")?;
    Ok(())
}

impl Config {
    /// Load `auditah.toml` from `root`. Returns default config if the file is
    /// absent (configuration is optional).
    ///
    /// # Errors
    ///
    /// Returns an error if the file exists but cannot be read or parsed.
    pub fn load(fs: &FsService, root: &Path) -> Result<Self, Report<ConfigError>> {
        let path = root.join(CONFIG_FILENAME);
        if !fs.exists(&path) {
            return Ok(Self::default());
        }
        let content = fs
            .read_to_string(&path)
            .change_context(ConfigError)
            .attach("failed to read project config")?;
        let cfg: Self = toml::from_str(&content)
            .change_context(ConfigError)
            .attach("failed to parse auditah.toml")
            .attach(path.display().to_string())?;
        validate_excludes(&cfg.exclude)?;
        Ok(cfg)
    }
}

/// Render a fully-commented `auditah.toml` template with default values, seeded
/// with the given acknowledged license ids.
///
/// Used by `init` (empty seed) and `ack` (when the file does not yet exist). The
/// template is hand-authored prose (matching the README canonical example) so it
/// carries explanatory comments; it round-trips through `Config::load` to defaults.
///
/// `init` passes an empty slice (defaults + empty arrays); `ack` passes the ids to
/// seed `manual_review_acknowledged` so a fresh project is ack-ready.
#[must_use]
pub fn render_config_template(ids: &[String]) -> String {
    let mut s = String::new();
    write_header(&mut s);
    write_commercial(&mut s);
    write_redistributes(&mut s);
    write_acknowledged(&mut s, ids);
    write_exclude(&mut s);
    s
}

/// Top-level header explaining the file's purpose.
#[allow(clippy::unwrap_used)] // writeln! to a String is infallible
fn write_header(s: &mut String) {
    writeln!(s, "# auditah project config.").unwrap();
    writeln!(s, "#").unwrap();
    writeln!(
        s,
        "# Optional: an absent auditah.toml yields the defaults shown below."
    )
    .unwrap();
    writeln!(s, "# Generated by `auditah init`.").unwrap();
    writeln!(s).unwrap();
}

#[allow(clippy::unwrap_used)] // writeln! to a String is infallible
fn write_commercial(s: &mut String) {
    writeln!(
        s,
        "# FAILs assets whose effective allows_commercial_use = false."
    )
    .unwrap();
    writeln!(s, "commercial_project = false").unwrap();
    writeln!(s).unwrap();
}

#[allow(clippy::unwrap_used)] // writeln! to a String is infallible
fn write_redistributes(s: &mut String) {
    writeln!(
        s,
        "# FAILs assets whose effective allows_redistribution = false."
    )
    .unwrap();
    writeln!(s, "redistributes_assets = false").unwrap();
    writeln!(s).unwrap();
}

/// `manual_review_acknowledged` array, optionally seeded with ids.
#[allow(clippy::unwrap_used)] // writeln! to a String is infallible
fn write_acknowledged(s: &mut String, ids: &[String]) {
    writeln!(
        s,
        "# SPDX ids whose manual_review obligation has been acknowledged."
    )
    .unwrap();
    if ids.is_empty() {
        writeln!(s, "manual_review_acknowledged = []").unwrap();
    } else {
        writeln!(s, "manual_review_acknowledged = [").unwrap();
        for id in ids {
            let entry = format!("    \"{id}\",");
            s.push_str(&entry);
            s.push('\n');
        }
        writeln!(s, "]").unwrap();
    }
    writeln!(s).unwrap();
}

#[allow(clippy::unwrap_used)] // writeln! to a String is infallible
fn write_exclude(s: &mut String) {
    writeln!(
        s,
        "# Additional glob patterns to exclude (merged after the built-in defaults)."
    )
    .unwrap();
    writeln!(s, "# Matched against paths relative to the project root.").unwrap();
    writeln!(s, "exclude = []").unwrap();
}

/// Append the given license ids to `manual_review_acknowledged` in an existing
/// `auditah.toml`, preserving all comments, formatting, and key order.
///
/// Uses `toml_edit::DocumentMut` (a lossless AST) so hand-edited comments survive.
/// Ids already present are skipped (idempotent). Ids absent from the array are
/// appended in order.
///
/// # Errors
///
/// Returns `ConfigError` if the file is not valid TOML or `manual_review_acknowledged`
/// exists but is not an array of strings.
pub fn ack_ids(content: &str, ids: &[String]) -> Result<String, Report<ConfigError>> {
    let mut doc: toml_edit::DocumentMut = content
        .parse()
        .change_context(ConfigError)
        .attach("failed to parse auditah.toml for ack")?;
    ensure_ack_array(&mut doc)?;
    let existing = collect_ack_strings(&doc);
    if let Some(arr) = doc["manual_review_acknowledged"].as_array_mut() {
        for id in ids {
            if !existing.iter().any(|e| e == id) {
                arr.push(id.as_str());
            }
        }
    }
    Ok(doc.to_string())
}

/// Ensure `manual_review_acknowledged` exists as an array. If absent, create it
/// (empty). If present but not an array of strings, error.
fn ensure_ack_array(doc: &mut toml_edit::DocumentMut) -> Result<(), Report<ConfigError>> {
    match doc.get("manual_review_acknowledged") {
        None => {
            doc["manual_review_acknowledged"] =
                toml_edit::Item::Value(toml_edit::Value::Array(toml_edit::Array::new()));
        }
        Some(item) => {
            if item.as_array().is_none() {
                return Err(Report::new(ConfigError)
                    .attach("manual_review_acknowledged must be an array of strings"));
            }
        }
    }
    Ok(())
}

/// Collect the existing string values from `manual_review_acknowledged`.
fn collect_ack_strings(doc: &toml_edit::DocumentMut) -> Vec<String> {
    doc.get("manual_review_acknowledged")
        .and_then(toml_edit::Item::as_array)
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(str::to_string))
                .collect()
        })
        .unwrap_or_default()
}

#[allow(clippy::unwrap_used, clippy::expect_used)]
#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_support::FakeFs;
    use std::path::Path;
    use std::sync::Arc;

    fn fs_with(files: &[(&str, &str)]) -> FsService {
        FsService::new(Arc::new(FakeFs::with_files(
            files.iter().map(|(p, c)| (*p, *c)),
        )))
    }

    #[test]
    fn missing_config_returns_default() {
        // Given a project with no auditah.toml.
        let fs = fs_with(&[]);

        // When loading the config.
        let cfg = Config::load(&fs, Path::new("/proj")).unwrap();

        // Then defaults are used (non-commercial, no redistribution, no acks, no excludes).
        assert!(!cfg.commercial_project);
        assert!(!cfg.redistributes_assets);
        assert!(cfg.manual_review_acknowledged.is_empty());
        assert!(cfg.exclude.is_empty());
    }

    #[test]
    fn commercial_flag_parses() {
        // Given a config with commercial_project = true.
        let fs = fs_with(&[("/proj/auditah.toml", "commercial_project = true\n")]);

        // When loading the config.
        let cfg = Config::load(&fs, Path::new("/proj")).unwrap();

        // Then the commercial flag is true.
        assert!(cfg.commercial_project);
    }

    #[test]
    fn exclude_globs_parse() {
        // Given a config with exclude globs.
        let fs = fs_with(&[(
            "/proj/auditah.toml",
            r#"
commercial_project = false
exclude = ["vendor/**", "*.bak"]
"#,
        )]);

        // When loading the config.
        let cfg = Config::load(&fs, Path::new("/proj")).unwrap();

        // Then the exclude globs parse into the expected vec.
        assert_eq!(cfg.exclude, vec!["vendor/**", "*.bak"]);
    }

    #[test]
    fn malformed_config_errors() {
        // Given a malformed auditah.toml.
        let fs = fs_with(&[("/proj/auditah.toml", "this is not = = valid toml")]);

        // When loading the config.
        let result = Config::load(&fs, Path::new("/proj"));

        // Then loading returns an error.
        assert!(result.is_err());
    }

    #[test]
    fn redistributes_assets_flag_parses() {
        // Given a config with redistributes_assets = true.
        let fs = fs_with(&[("/proj/auditah.toml", "redistributes_assets = true\n")]);

        // When loading the config.
        let cfg = Config::load(&fs, Path::new("/proj")).unwrap();

        // Then the redistribution flag is true.
        assert!(cfg.redistributes_assets);
    }

    #[test]
    fn manual_review_acknowledged_list_parses() {
        // Given a config with an acknowledged license id.
        let fs = fs_with(&[(
            "/proj/auditah.toml",
            "manual_review_acknowledged = [\"LicenseRef-StudioEULA\", \"LicenseRef-Other\"]\n",
        )]);

        // When loading the config.
        let cfg = Config::load(&fs, Path::new("/proj")).unwrap();

        // Then both acknowledged ids parse into the vec.
        assert_eq!(
            cfg.manual_review_acknowledged,
            vec!["LicenseRef-StudioEULA", "LicenseRef-Other"]
        );
    }

    #[test]
    fn invalid_exclude_glob_fails_fast_at_config_load() {
        // Given an auditah.toml with an invalid exclude glob.
        let fs = fs_with(&[("/proj/auditah.toml", "exclude = [\"**/[invalid\"]\n")]);

        // When loading the config.
        let result = Config::load(&fs, Path::new("/proj"));

        // Then loading errors eagerly (glob validated at config load).
        assert!(
            result.is_err(),
            "invalid exclude glob must fail fast at Config::load"
        );
    }

    #[test]
    fn valid_exclude_globs_load_and_preserve() {
        // Given an auditah.toml with valid exclude globs.
        let fs = fs_with(&[(
            "/proj/auditah.toml",
            "exclude = [\"vendor/**\", \"*.bak\"]\n",
        )]);

        // When loading the config.
        let cfg = Config::load(&fs, Path::new("/proj")).unwrap();

        // Then the globs validate and are preserved unchanged.
        assert_eq!(cfg.exclude, vec!["vendor/**", "*.bak"]);
    }

    #[test]
    fn render_config_template_round_trips_to_defaults() {
        // Given a template rendered with no seed ids.
        let rendered = render_config_template(&[]);

        // When loading it through Config::load.
        let fs = fs_with(&[("/proj/auditah.toml", &rendered)]);
        let cfg = Config::load(&fs, Path::new("/proj")).unwrap();

        // Then it parses to Config::default().
        assert_eq!(cfg, Config::default());
    }

    #[test]
    fn render_config_template_contains_field_comments() {
        // Given a template rendered with no seed ids.
        let rendered = render_config_template(&[]);

        // Then each field's explanatory comment is present.
        assert!(rendered.contains("# FAILs assets whose effective allows_commercial_use = false."));
        assert!(rendered.contains("# FAILs assets whose effective allows_redistribution = false."));
        assert!(
            rendered.contains("# SPDX ids whose manual_review obligation has been acknowledged.")
        );
        assert!(rendered.contains("# Additional glob patterns to exclude"));
    }

    #[test]
    fn render_config_template_seeds_ack_ids() {
        // Given a template rendered with a seed id.
        let rendered = render_config_template(&["LicenseRef-Foo".to_string()]);

        // When loading it.
        let fs = fs_with(&[("/proj/auditah.toml", &rendered)]);
        let cfg = Config::load(&fs, Path::new("/proj")).unwrap();

        // Then the seed id is in manual_review_acknowledged.
        assert_eq!(cfg.manual_review_acknowledged, vec!["LicenseRef-Foo"]);
    }

    #[test]
    fn ack_ids_appends_to_existing_array() {
        // Given an existing auditah.toml with a comment + empty ack array.
        let original = "# my project\nmanual_review_acknowledged = []\n";

        // When appending an id.
        let result = ack_ids(original, &["LicenseRef-Foo".to_string()]).unwrap();

        // Then the id is present and the comment survives.
        assert!(result.contains("LicenseRef-Foo"));
        assert!(result.contains("# my project"));
    }

    #[test]
    fn ack_ids_is_idempotent() {
        // Given an auditah.toml already containing the id.
        let original = "manual_review_acknowledged = [\"LicenseRef-Foo\"]\n";

        // When appending the same id.
        let result = ack_ids(original, &["LicenseRef-Foo".to_string()]).unwrap();

        // Then the id appears exactly once.
        assert_eq!(result.matches("LicenseRef-Foo").count(), 1);
    }

    #[test]
    fn ack_ids_preserves_other_fields() {
        // Given an auditah.toml with commercial flag and exclude set.
        let original =
            "commercial_project = true\nexclude = [\"vendor/**\"]\nmanual_review_acknowledged = []\n";

        // When appending an id.
        let result = ack_ids(original, &["LicenseRef-Foo".to_string()]).unwrap();

        // Then the other fields are unchanged.
        assert!(result.contains("commercial_project = true"));
        assert!(result.contains("exclude = [\"vendor/**\"]"));
    }

    #[test]
    fn ack_ids_errors_on_malformed_input() {
        // Given malformed TOML.
        let original = "this is not = = valid toml";

        // When appending an id.
        let result = ack_ids(original, &["LicenseRef-Foo".to_string()]);

        // Then it errors.
        assert!(result.is_err());
    }
}
